# Generated by Django 6.0.5 on 2026-05-25 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_scholar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_platform_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_message',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_role', models.CharField(choices=[('judge', 'Judge'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer'), ('evaluator', 'Evaluator'), ('friend', 'Friend')], default='friend', max_length=20)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver', 'suggested_role')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.evaluation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'evaluation', 'code')},
            },
        ),
    ]
