# Generated by Django 6.0.5 on 2026-05-25 23:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_gamification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('label_normalization', 'Semantic label normalization'), ('effort_routing', 'Effort estimation and queue routing'), ('codebook_induction', 'Codebook induction'), ('disagreement_diagnosis', 'Disagreement diagnosis'), ('consistency_audit', 'Intra-judge consistency audit'), ('threats_validity', 'Threats-to-validity report')], max_length=40)),
                ('provider', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(max_length=80)),
                ('input_hash', models.CharField(max_length=64)),
                ('prompt', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_runs', to='core.dataset')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_runs', to='core.evaluation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabelNormalizationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_column', models.CharField(max_length=200)),
                ('distinct_labels', models.JSONField(blank=True, default=list)),
                ('proposed_mapping', models.JSONField(blank=True, default=dict)),
                ('approved_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_normalization_proposals', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_normalization_proposals', to='core.dataset')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_label_normalizations', to=settings.AUTH_USER_MODEL)),
                ('llm_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_normalization_proposals', to='core.llmrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisagreementDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, max_length=80)),
                ('explanation', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagreement_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagreement_diagnoses', to='core.evaluation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagreement_diagnoses', to='core.datasetitem')),
                ('llm_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disagreement_diagnoses', to='core.llmrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsistencyFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_a', models.CharField(max_length=200)),
                ('label_b', models.CharField(max_length=200)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('corrected', 'Corrected'), ('genuinely_different', 'Genuinely different'), ('dismissed', 'Dismissed')], default='open', max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_consistency_findings', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_findings', to='core.evaluation')),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_findings_as_a', to='core.datasetitem')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_findings_as_b', to='core.datasetitem')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_findings', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_consistency_findings', to=settings.AUTH_USER_MODEL)),
                ('llm_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_findings', to='core.llmrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Codebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('markdown', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_codebooks', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codebooks', to='core.evaluation')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_codebooks', to=settings.AUTH_USER_MODEL)),
                ('llm_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codebooks', to='core.llmrun')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_scores', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_suggestions', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_routing_suggestions', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_suggestions', to='core.evaluation')),
                ('llm_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_suggestions', to='core.llmrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatsValidityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_snapshot', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('markdown', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_reports', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_reports', to='core.evaluation')),
                ('llm_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_reports', to='core.llmrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
