# Generated by Django 5.2.14 on 2026-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_public_evaluations_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('profile', 'Profile'), ('evaluation_invite', 'Evaluation invite'), ('evaluation', 'Evaluation'), ('follow', 'Follow'), ('chat', 'Chat'), ('points', 'Points'), ('activity', 'Activity')], max_length=40),
        ),
    ]
